x=5
print(x)

try:
    print(z)  # z is not defined so exception is handled using try block
except:
    print("variable is not defined") # except says what have to do